export const EMPLOYEEPOSTDATAPENDING = "EMPLOYEEPOSTDATAPENDING";
export const EMPLOYEEPOSTDATASUCESSS = "EMPLOYEEPOSTDATASUCESSS";
export const EMPLOYEEPOSTDATAFailure = "EMPLOYEEPOSTDATAFailure";

export const EMPLOYEEPOSTATTACHMENTPENDING = "EMPLOYEEPOSTATTACHMENTPENDING";
export const EMPLOYEEPOSTATTACHMENTSUCESSS = "EMPLOYEEPOSTATTACHMENTSUCESSS";
export const EMPLOYEEPOSTATTACHMENTFailure = "EMPLOYEEPOSTATTACHMENTFailure";

export const GETDATAREQ = "GETDATAREQ";
export const GETDATASUCESSS = "GETDATASUCESSS";
export const GETDATAFailure = "GETDATAFailure";

export const GETDATASINGLEREQ = "GETDATASINGLEREQ";
export const GETDATASINGLESUCESSS = "GETDATASINGLESUCESSS";
export const GETDATASINGLEFailure = "GETDATASINGLEFailure";

{
  /*** When HR updates Candidate information Phase One   */
}

export const UPDATESINGLEEMPLOYEEEREQ = "UPDATESINGLEEMPLOYEEEREQ";
export const UPDATESINGLEEMPLOYEEESUCESSS = "UPDATESINGLEEMPLOYEEESUCESSS";
export const UPDATESINGLEEMPLOYEEEFailure = "UPDATESINGLEEMPLOYEEEFailure";

{
  /*** When HR Reject Candidate information Phase One   */
}

export const HRREJECTPHASEONEEMPLOYEEEREQ = "HRREJECTPHASEONEEMPLOYEEEREQ";
export const HRREJECTPHASEONEEMPLOYEEESUCESSS =
  "HRREJECTPHASEONEEMPLOYEEESUCESSS";
export const HRREJECTPHASEONEEMPLOYEEEFailure =
  "HRREJECTPHASEONEEMPLOYEEEFailure";

// Load particular candidate information for Phase 2 filling

export const GETCANDIDATEINFOREQ = "GETCANDIDATEINFOREQ";
export const GETCANDIDATEINFOSUCESSS = "GETCANDIDATEINFOSUCESSS";
export const GETCANDIDATEINFOFAILURE = "GETCANDIDATEINFOFAILURE";


//  Employee Attachment Status

export const EMPLOYEEATTACHMENTSTATUSPENDING =
  "EMPLOYEEATTACHMENTSTATUSPENDING";
export const EMPLOYEEATTACHMENTSTATUSSUCESSS =
  "EMPLOYEEATTACHMENTSTATUSSUCESSS";
export const EMPLOYEEATTACHMENTSTATUSFailure =
  "EMPLOYEEATTACHMENTSTATUSFailure";


//  Employeee get documets status


export const EMPLOYEEPUTSEONDPHASEPENDING = "EMPLOYEEPUTSEONDPHASEPENDING";
export const EMPLOYEEPUTSEONDPHASESUCESSS = "EMPLOYEEPUTSEONDPHASESUCESSS";
export const EMPLOYEEPUTSEONDPHASEFailure = "EMPLOYEEPUTSEONDPHASEFailure";
