

// Load particular IDCARD  get  details

export const IDCARDGETREQ     = "IDCARDGETREQ";
export const IDCARDGETSUCCESS = "IDCARDGETSUCCESS";
export const IDCARDGETFAILURE = "IDCARDGETFAILURE";




// Load particular  UserIdCARD  get  details

export const USERIDCARDGETREQ     = "USERIDCARDGETREQ";
export const USERIDCARDGETSUCCESS = "USERIDCARDGETSUCCESS";
export const USERIDCARDGETFAILURE = "USERIDCARDGETFAILURE";


// Load particular  EmployeeVerification  get  details

export const EMPLOYEEVERIFICATIONGETREQ     = "EMPLOYEEVERIFICATIONGETREQ";
export const EMPLOYEEVERIFICATIONGETSUCCESS = "EMPLOYEEVERIFICATIONGETSUCCESS";
export const EMPLOYEEVERIFICATIONGETFAILURE = "EMPLOYEEVERIFICATIONGETFAILURE";


//  Personal details 

export const EMPLOYEEPERSONALDEATILSGETREQ     = "EMPLOYEEPERSONALDEATILSGETREQ";
export const EMPLOYEEPERSONALDEATILSGETSUCCESS = "EMPLOYEEPERSONALDEATILSGETSUCCESS";
export const EMPLOYEEPERSONALDEATILSGETFAILURE = "EMPLOYEEPERSONALDEATILSGETFAILURE";


//  Application details 

export const CANDIDATEAPPLICANTGETREQ     = "CANDIDATEAPPLICANTGETREQ";
export const CANDIDATEAPPLICANTGETSUCCESS = "CANDIDATEAPPLICANTGETSUCCESS";
export const CANDIDATEAPPLICANTGETFAILURE = "CANDIDATEAPPLICANTGETFAILURE";



//  Decalartion form details 

export const CANDIDATEDECALARTIONFORMGETREQ     = "CANDIDATEDECALARTIONFORMGETREQ";
export const CANDIDATEDECALARTIONFORMGETSUCCESS = "CANDIDATEDECALARTIONFORMGETSUCCESS";
export const CANDIDATEDECALARTIONFORMGETFAILURE = "CANDIDATEDECALARTIONFORMGETFAILURE";


//  Decalartion form details 

export const CANDIDATEEPFNOMINEEGETREQ     = "CANDIDATEEPFNOMINEEGETREQ";
export const CANDIDATEEPFNOMINEEGETSUCCESS = "CANDIDATEEPFNOMINEEGETSUCCESS";
export const CANDIDATEEPFNOMINEEGETFAILURE = "CANDIDATEEPFNOMINEEGETFAILURE";

//  Nominee POST form details 

export const CANDIDATEEPFNOMINEEPOSTREQ     = "CANDIDATEEPFNOMINEEPOSTREQ";
export const CANDIDATEEPFNOMINEEPOSTSUCCESS = "CANDIDATEEPFNOMINEEPOSTSUCCESS";
export const CANDIDATEEPFNOMINEEPOSTFAILURE = "CANDIDATEEPFNOMINEEPOSTFAILURE";